In [ ]:
import pandas as pd
import numpy as np

# Create the first DataFrame
df1 = pd.DataFrame({
    'Student_ID': [101, 102, 103, 104],
    'Name': ['Anu', 'Ravi', 'Manu', 'Priya'],
    'Marks': [85, 90, 78, 92],
    'Department': ['CSE', 'ECE', 'CSE', 'IT']
})

# Create the second DataFrame
df2 = pd.DataFrame({
    'Student_ID': [101, 102, 103, 105],
    'Age': [19, 20, 21, 19],
    'City': ['Vizag', 'Hyderabad', 'Vijayawada', 'Guntur']
})

print("DataFrame 1:")
display(df1)

print("DataFrame 2:")
display(df2)

DataFrame 1:

   Student_ID   Name  Marks Department
0         101    Anu     85        CSE
1         102   Ravi     90        ECE
2         103   Manu     78        CSE
3         104  Priya     92         IT

DataFrame 2:

   Student_ID  Age        City
0         101   19       Vizag
1         102   20   Hyderabad
2         103   21  Vijayawada
3         105   19      Guntur

In [ ]:
#Hierarchical Indexing (MultiIndex)

#Hierarchical indexing allows you to have multiple index levels in a DataFrame.
data = {
    'Marks': [85, 90, 78, 92],
    'Attendance': [90, 95, 85, 98]
}

index = [
    ['CSE', 'CSE', 'ECE', 'ECE'],
    ['Anu', 'Ravi', 'Manu', 'Priya']
]

df = pd.DataFrame(
    data,
    index=index
)

df.index.names = ['Department', 'Student']

print(df)

                    Marks  Attendance
Department Student
CSE        Anu         85          90
           Ravi        90          95
ECE        Manu        78          85
           Priya       92          98

In [ ]:
#Access Data Using Hierarchical Indexing
# Access all students in CSE
print(df.loc['CSE'])

# Access the marks of Anu
print(df.loc[('CSE', 'Anu'), 'Marks'])

         Marks  Attendance
Student
Anu         85          90
Ravi        90          95
85

In [ ]:
#Swap Index Levels
print(df.swaplevel())

                    Marks  Attendance
Student Department
Anu     CSE            85          90
Ravi    CSE            90          95
Manu    ECE            78          85
Priya   ECE            92          98

In [ ]:
#Sort the Hierarchical Index
print(df.sort_index())

                    Marks  Attendance
Department Student
CSE        Anu         85          90
           Ravi        90          95
ECE        Manu        78          85
           Priya       92          98

In [ ]:
#Vertical Concatenation

#Adds rows one below another.

df1 = pd.DataFrame({
    'Name': ['Anu', 'Ravi'],
    'Marks': [85, 90]
})

df2 = pd.DataFrame({
    'Name': ['Manu', 'Priya'],
    'Marks': [78, 92]
})

result = pd.concat([df1, df2], axis=0, ignore_index=True)

print(result)

    Name  Marks
0    Anu     85
1   Ravi     90
2   Manu     78
3  Priya     92

In [ ]:
#Horizontal Concatenation

#Adds columns side by side.

df1 = pd.DataFrame({
    'Name': ['Anu', 'Ravi', 'Manu']
})

df2 = pd.DataFrame({
    'Marks': [85, 90, 78]
})

result = pd.concat([df1, df2], axis=1)

print(result)

   Name  Marks
0   Anu     85
1  Ravi     90
2  Manu     78

In [ ]:
#Merging DataFrames

#The merge() function combines DataFrames using a common column.

students = pd.DataFrame({
    'Student_ID': [101, 102, 103],
    'Name': ['Anu', 'Ravi', 'Manu']
})

marks = pd.DataFrame({
    'Student_ID': [101, 102, 104],
    'Marks': [85, 90, 95]
})

result = pd.merge(students, marks, on='Student_ID', how='inner')

print(result)

   Student_ID  Name  Marks
0         101   Anu     85
1         102  Ravi     90

In [ ]:
# Inner merge
print(pd.merge(students, marks, on='Student_ID', how='inner'))

# Left merge
print(pd.merge(students, marks, on='Student_ID', how='left'))

# Right merge
print(pd.merge(students, marks, on='Student_ID', how='right'))

# Outer merge
print(pd.merge(students, marks, on='Student_ID', how='outer'))

   Student_ID  Name  Marks
0         101   Anu     85
1         102  Ravi     90
   Student_ID  Name  Marks
0         101   Anu   85.0
1         102  Ravi   90.0
2         103  Manu    NaN
   Student_ID  Name  Marks
0         101   Anu     85
1         102  Ravi     90
2         104   NaN     95
   Student_ID  Name  Marks
0         101   Anu   85.0
1         102  Ravi   90.0
2         103  Manu    NaN
3         104   NaN   95.0

In [ ]:
#Reshaping DataFrames

#The melt() function converts data from wide format to long format.

df = pd.DataFrame({
    'Student': ['Anu', 'Ravi', 'Manu'],
    'Python': [85, 90, 78],
    'Java': [80, 88, 82]
})

print("Original DataFrame:")
display(df)

result = pd.melt(
    df,
    id_vars=['Student'],
    var_name='Subject',
    value_name='Marks'
)

print("After Melt:")
display(result)

Original DataFrame:

  Student  Python  Java
0     Anu      85    80
1    Ravi      90    88
2    Manu      78    82

After Melt:

  Student Subject  Marks
0     Anu  Python     85
1    Ravi  Python     90
2    Manu  Python     78
3     Anu    Java     80
4    Ravi    Java     88
5    Manu    Java     82

In [ ]:
#The stack() method moves columns into the inner row index, producing a Series in this example.

df = pd.DataFrame({
    'Python': [85, 90],
    'Java': [80, 88]
}, index=['Anu', 'Ravi'])

result = df.stack()

print(result)

Anu   Python    85
      Java      80
Ravi  Python    90
      Java      88
dtype: int64

In [ ]:
#The unstack() method moves an index level into columns.

result = df.stack().unstack()

print(result)

      Python  Java
Anu       85    80
Ravi      90    88

In [ ]:
#The pivot() function rearranges data by turning unique values from one column into separate columns.

df = pd.DataFrame({
    'Student': ['Anu', 'Anu', 'Ravi', 'Ravi'],
    'Subject': ['Python', 'Java', 'Python', 'Java'],
    'Marks': [85, 80, 90, 88]
})

print("Original DataFrame:")
display(df)

result = df.pivot(
    index='Student',
    columns='Subject',
    values='Marks'
)

print("After Pivot:")
display(result)

Original DataFrame:

  Student Subject  Marks
0     Anu  Python     85
1     Anu    Java     80
2    Ravi  Python     90
3    Ravi    Java     88

After Pivot:

Subject  Java  Python
Student
Anu        80      85
Ravi       88      90

In [ ]:
#Pivot Table Using pivot_table()

#The pivot_table() function summarizes data and can aggregate duplicate combinations.

df = pd.DataFrame({
    'Department': ['CSE', 'CSE', 'ECE', 'ECE', 'CSE'],
    'Subject': ['Python', 'Python', 'Java', 'Java', 'Java'],
    'Marks': [80, 90, 75, 85, 95]
})

result = df.pivot_table(
    index='Department',
    columns='Subject',
    values='Marks',
    aggfunc='mean'
)

print(result)

Subject     Java  Python
Department
CSE         95.0    85.0
ECE         80.0     NaN

In [ ]:
#Crosstabulation Using crosstab()

#The pd.crosstab() function calculates frequencies for combinations of categorical variables.

df = pd.DataFrame({
    'Department': ['CSE', 'CSE', 'ECE', 'ECE', 'CSE'],
    'Gender': ['F', 'M', 'F', 'M', 'F']
})

result = pd.crosstab(df['Department'], df['Gender'])

print(result)

Gender      F  M
Department
CSE         2  1
ECE         1  1

In [ ]:
#Rename Columns

#The rename() method changes column names or index labels.

df = pd.DataFrame({
    'Student_Name': ['Anu', 'Ravi'],
    'Student_Marks': [85, 90]
})

result = df.rename(columns={
    'Student_Name': 'Name',
    'Student_Marks': 'Marks'
})

print(result)

   Name  Marks
0   Anu     85
1  Ravi     90

In [ ]:
#Sorting DataFrames

#The sort_values() method sorts rows using column values.

df = pd.DataFrame({
    'Name': ['Anu', 'Ravi', 'Manu'],
    'Marks': [85, 90, 78]
})

# Sort in ascending order
print(df.sort_values(by='Marks'))

# Sort in descending order
print(df.sort_values(by='Marks', ascending=False))

   Name  Marks
2  Manu     78
0   Anu     85
1  Ravi     90
   Name  Marks
1  Ravi     90
0   Anu     85
2  Manu     78

In [ ]:
#Dropping Duplicate Rows

#The drop_duplicates() method removes duplicate records.

df = pd.DataFrame({
    'Name': ['Anu', 'Ravi', 'Anu', 'Manu'],
    'Marks': [85, 90, 85, 78]
})

result = df.drop_duplicates()

print(result)

   Name  Marks
0   Anu     85
1  Ravi     90
3  Manu     78

In [1]:
# Demonstration of all types of joins in pandas
import pandas as pd

# Create sample DataFrames
df1 = pd.DataFrame({
    'Student_ID': [101, 102, 103, 104],
    'Name': ['Anu', 'Ravi', 'Manu', 'Priya']
})

df2 = pd.DataFrame({
    'Student_ID': [101, 102, 103, 105],
    'City': ['Vizag', 'Hyderabad', 'Vijayawada', 'Guntur']
})

print("DataFrame 1:")
display(df1)

print("\nDataFrame 2:")
display(df2)

# 1. Inner Join (Returns only matching rows in both DataFrames)
inner_join = pd.merge(df1, df2, on='Student_ID', how='inner')
print("\nInner Join:")
display(inner_join)

# 2. Left Join (Returns all rows from the left DataFrame, and matched rows from the right)
left_join = pd.merge(df1, df2, on='Student_ID', how='left')
print("\nLeft Join:")
display(left_join)

# 3. Right Join (Returns all rows from the right DataFrame, and matched rows from the left)
right_join = pd.merge(df1, df2, on='Student_ID', how='right')
print("\nRight Join:")
display(right_join)

# 4. Outer Join (Returns all rows when there is a match in either left or right DataFrame)
outer_join = pd.merge(df1, df2, on='Student_ID', how='outer')
print("\nOuter Join:")
display(outer_join)

DataFrame 1:

   Student_ID   Name
0         101    Anu
1         102   Ravi
2         103   Manu
3         104  Priya

DataFrame 2:

   Student_ID        City
0         101       Vizag
1         102   Hyderabad
2         103  Vijayawada
3         105      Guntur

Inner Join:

   Student_ID  Name        City
0         101   Anu       Vizag
1         102  Ravi   Hyderabad
2         103  Manu  Vijayawada

Left Join:

   Student_ID   Name        City
0         101    Anu       Vizag
1         102   Ravi   Hyderabad
2         103   Manu  Vijayawada
3         104  Priya         NaN

Right Join:

   Student_ID  Name        City
0         101   Anu       Vizag
1         102  Ravi   Hyderabad
2         103  Manu  Vijayawada
3         105   NaN      Guntur

Outer Join:

   Student_ID   Name        City
0         101    Anu       Vizag
1         102   Ravi   Hyderabad
2         103   Manu  Vijayawada
3         104  Priya         NaN
4         105    NaN      Guntur